services:
  warehouse:
    build: .
    ports:
      - 8080:8080

  mysql:
    image: mysql:8
    ports:
      - 8083:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./warehouse/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse

  redis:
    image: redis
    ports:
      - 6380:6379

volumes:
  mysql-data:
